# Cloud Build configuration for Flutter Frontend
# Builds Docker image and deploys to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/reed-refactor-v1-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/reed-refactor-v1-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/reed-refactor-v1-frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/reed-refactor-v1-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'reed-refactor-v1-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/reed-refactor-v1-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'API_URL=https://reed-refactor-v1-backend-${PROJECT_NUMBER}-uw.a.run.app'

images:
  - 'gcr.io/$PROJECT_ID/reed-refactor-v1-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/reed-refactor-v1-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

